# Site settings
title: Pop Culture Perspectives
email: eric.rovtar@me.com
description: "Sometimes there are things hidden right in plain sight. We only need to look for them, so that's what I do. I examine pop culture - movies, video games, tv shows - and find the deeper meanings within them."
baseurl: ""
url: "http://ericrovtar.com"
twitterUrl: "http://twitter.com/ericrovtar"
facebookUrl: "http://facebook.com/eric.rovtar"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
